// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/quil/Projects/nextgen/RemarkableSports-UI/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/quil/Projects/nextgen/RemarkableSports-UI/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Remarkable Sport', appParameters);
});
require('/Users/quil/Projects/nextgen/RemarkableSports-UI/index.js');