import { StyleSheet } from "react-native";
import { SCREEN_WIDTH } from "../../../constants/constants";

const styles = StyleSheet.create({
  districtModalContainer: {
    justifyContent: "flex-end",
    marginLeft: 0,
    marginRight: 0,
  },
  districtModalContent: {
    backgroundColor: "white",
    padding: 16,
    justifyContent: "center",
  },
  timePickerContainer: {
    justifyContent: "flex-end",
    marginLeft: 0,
    marginRight: 0,
  },
  timePickerContent: { backgroundColor: "white", padding: 16 },
  sectionContainer: { marginTop: 32, flexDirection: "column" },
  sectionText: { fontWeight: "700", fontSize: 20, marginBottom: 16 },
  sectionContentContainer: {
    height: 64,
    backgroundColor: "white",
    borderRadius: 16,
    justifyContent: "space-between",
    paddingVertical: 20,
    paddingHorizontal: 20,
    shadowOffset: { width: 5, height: 5 },
    shadowColor: "#0000001a",
    shadowOpacity: 1,
    shadowRadius: 2,
    borderColor: "#0000001a",
    flexDirection: "row",
    alignItems: "center",
    elevation: 3,
  },
  sectionPlaceHolder: { color: "#8D8D8D", fontSize: 16 },
  sectionValue: { fontSize: 16 },
  sectionContainer2: { marginTop: 16, flexDirection: "column" },
  timeSectionContainer: {
    backgroundColor: "white",
    marginTop: 16,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 20,
    shadowOffset: { width: 5, height: 5 },
    shadowColor: "#0000001a",
    shadowOpacity: 1,
    shadowRadius: 2,
    borderColor: "#0000001a",
    flexDirection: "column",
    justifyContent: "center",
    elevation: 3,
  },
  timePlacerHolder: {
    fontWeight: "400",
    fontSize: 12,
    marginBottom: 4,
    color: "#8D8D8D",
  },
  timeValue: { fontWeight: "400", fontSize: 16 },
  toTimePlaceHolder: {
    fontWeight: "400",
    fontSize: 12,
    marginBottom: 4,
    color: "#8D8D8D",
  },
  trackStyle: { height: 10, borderRadius: 10, backgroundColor: "#F8F8F8" },
  trackItemContainer: {
    height: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  trackItem: {
    height: 30,
    width: 30,
    borderRadius: 20,
    backgroundColor: "#31095E",
  },
  backIcon: { width: 16, height: 16 },
  headerStyle: { fontWeight: "700", fontSize: 16 },
  headerContainer: {
    justifyContents: "center",
    alignItems: "center",
  },
  pickerStyle: {
    zIndex: 999,
    marginTop: 14,
    borderRadius: 16,
    padding: 0,
    flexDirection: "row",
    color: "purple",
    alignItems: "center",
    backgroundColor: "white",
    shadowOffset: { width: 5, height: 5 },
    shadowColor: "#0000001a",
    shadowOpacity: 1,
    shadowRadius: 2,
    justifyContent: "center",
    elevation: 3,
    borderWidth: 0,
  },
  placeholderStyle: {
    color: "#9A9A9A",
    fontSize: 16,
    padding: 20,
    paddingLeft: 10,
    alignItems: "center",
  },
  formInput: {
    backgroundColor: "white",
    shadowOffset: { width: 5, height: 5 },
    shadowColor: "#0000001a",
    shadowOpacity: 1,
    shadowRadius: 2,
    borderRadius: 16,
    marginTop: 0,
  },
  ballProvidedText: {
    color: "#000000",
    padding: 16,
    paddingLeft: 10,
    paddingTop: 22,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  venuePhotoContainer: {
    flex: 1,
    height: 200,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    shadowOffset: { width: 5, height: 5 },
    shadowColor: "#0000001a",
    shadowOpacity: 1,
    shadowRadius: 2,
    backgroundColor: "white",
    elevation: 3,
  },
  venueImage: {
    width: SCREEN_WIDTH * 0.9,
    height: 200,
    borderRadius: 16,
  },
  uploadTextStyle: {
    fontSize: 16,
    color: "#979797",
  },
});

export default styles;
